language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.0.0

script:
  - dotnet restore
  - dotnet build
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet pack . --configuration Release /p:Version=$TRAVIS_TAG;
  nuget push ./bin/Release/*.nupkg -ApiKey $NUGET_API_KEY;
  fi"